from __future__ import annotations

import argparse
from pathlib import Path
from typing import Iterable

from spmt.converter import convert_parse_result
from spmt.documenter import write_learning_docs, write_migration_report
from spmt.ktr_generator import SqlBlock, generate_ktr, write_ktr
from spmt.parser import parse_file, parse_string
from spmt.table_mapper import TableMapper
from spmt.variable_handler import VariableHandler


def _repo_root() -> Path:
    return Path(__file__).resolve().parent.parent


def _config_path(filename: str) -> Path:
    return _repo_root() / "config" / filename


def _default_variable_handler() -> VariableHandler:
    config_file = _config_path("variable_mappings.json")
    if config_file.exists():
        return VariableHandler(str(config_file))
    return VariableHandler()


def _default_table_mapper() -> TableMapper:
    config_file = _config_path("table_mappings.json")
    if config_file.exists():
        return TableMapper.from_config(config_file)
    return TableMapper({}, default_schema="", default_prefix="")


def _iter_input_files(input_path: Path) -> Iterable[Path]:
    if input_path.is_file():
        yield input_path
        return

    if input_path.is_dir():
        yield from sorted(input_path.rglob("*.sas"))
        return

    raise FileNotFoundError(f"Input path not found: {input_path}")


def _output_base(input_file: Path, input_root: Path, output_dir: Path) -> Path:
    if input_root.is_dir():
        relative = input_file.relative_to(input_root).with_suffix("")
        return output_dir / relative
    return output_dir / input_file.stem


def _write_sql(output_path: Path, result) -> Path:
    output_path.parent.mkdir(parents=True, exist_ok=True)

    sections = []
    if result.drop_statements:
        sections.append("-- Drop statements")
        sections.extend(result.drop_statements)

    for block in result.blocks:
        header = f"-- Block {block.block_number:02d}"
        if block.target_table:
            header += f" -> {block.target_table}"
        sections.append(header)
        sections.append(block.converted_sql.rstrip())

    output_path.write_text("\n\n".join(sections).rstrip() + "\n", encoding="utf-8")
    return output_path


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="spmt",
        description="Convert SAS PROC SQL blocks into Oracle SQL, Pentaho KTR files, and markdown reports.",
    )
    parser.add_argument("input_path", help="Path to a .sas file or a directory of .sas files")
    parser.add_argument(
        "--output",
        default="output",
        help="Directory where converted files are written (default: output)",
    )
    parser.add_argument(
        "--format",
        choices=("sql", "ktr", "both"),
        default="both",
        help="What to generate (default: both)",
    )
    parser.add_argument(
        "--no-report",
        action="store_true",
        help="Skip migration report generation",
    )
    parser.add_argument(
        "--no-learn",
        action="store_true",
        help="Skip learning docs generation",
    )
    parser.add_argument(
        "--transformation-name",
        default="SPMT_Migration",
        help="Pentaho transformation name (default: SPMT_Migration)",
    )
    parser.add_argument(
        "--description",
        default="Auto-generated by SPMT from SAS PROC SQL source",
        help="Pentaho transformation description",
    )
    parser.add_argument(
        "--connection-name",
        default="oracle_dwh",
        help="Pentaho database connection name",
    )
    parser.add_argument("--host", default="localhost", help="Oracle host for the KTR placeholder")
    parser.add_argument("--port", default="1521", help="Oracle port for the KTR placeholder")
    parser.add_argument("--db-name", default="ORCL", help="Oracle database name for the KTR placeholder")
    parser.add_argument("--schema", default="", help="Default schema shown in the KTR placeholder")
    parser.add_argument("--username", default="dwh_user", help="Oracle username shown in the KTR placeholder")
    return parser


def convert_sas_to_oracle(sas_code: str) -> str:
    """The in-memory conversion helper described in the application flow."""
    parse_result = parse_string(sas_code)
    conversion_result = convert_parse_result(
        parse_result,
        variable_handler=_default_variable_handler(),
        table_mapper=_default_table_mapper(),
    )
    return "\n\n".join(block.converted_sql for block in conversion_result.blocks)


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)

    input_path = Path(args.input_path).expanduser().resolve()
    output_dir = Path(args.output).expanduser().resolve()
    output_dir.mkdir(parents=True, exist_ok=True)

    variable_handler = _default_variable_handler()
    table_mapper = _default_table_mapper()

    input_files = list(_iter_input_files(input_path))
    if not input_files:
        raise SystemExit(f"No .sas files found under: {input_path}")

    for input_file in input_files:
        parse_result = parse_file(input_file)
        conversion_result = convert_parse_result(
            parse_result,
            variable_handler=variable_handler,
            table_mapper=table_mapper,
        )

        base_path = _output_base(input_file, input_path, output_dir)

        if args.format in ("sql", "both"):
            sql_path = _write_sql(base_path.with_suffix(".sql"), conversion_result)
            print(f"Wrote SQL: {sql_path}")

        if args.format in ("ktr", "both"):
            ktr_blocks = [
                SqlBlock(
                    block_number=block.block_number,
                    converted_sql=block.converted_sql,
                    source_table=block.target_table,
                    rules_applied=block.rules_applied,
                )
                for block in conversion_result.blocks
            ]
            ktr_result = generate_ktr(
                ktr_blocks,
                transformation_name=args.transformation_name,
                description=args.description,
                connection_name=args.connection_name,
                connection_config={
                    "host": args.host,
                    "port": args.port,
                    "db_name": args.db_name,
                    "schema": args.schema,
                    "username": args.username,
                },
            )
            ktr_path = write_ktr(ktr_result, base_path.with_suffix(".ktr"))
            print(f"Wrote KTR: {ktr_path}")

        if not args.no_report:
            report_path = write_migration_report(
                conversion_result,
                base_path.with_name(f"{base_path.name}_migration_report.md"),
            )
            print(f"Wrote report: {report_path}")

        if not args.no_learn:
            learn_path = write_learning_docs(
                conversion_result,
                base_path.with_name(f"{base_path.name}_learning_docs.md"),
            )
            print(f"Wrote learning docs: {learn_path}")

        warning_count = sum(len(block.warnings) for block in conversion_result.blocks) + len(conversion_result.warnings)
        print(
            f"Summary for {input_file.name}: "
            f"{len(conversion_result.blocks)} blocks converted, "
            f"{sum(len(block.rules_applied) for block in conversion_result.blocks)} rules applied, "
            f"{warning_count} warnings"
        )

    return 0


if __name__ == "__main__":
    raise SystemExit(main())